name: Obfuscate and Commit

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  obfuscate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install -g javascript-obfuscator

      - name: Obfuscate code
        run: |
          javascript-obfuscator index.js --output _worker.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _worker.js
          git commit -m "Obfuscate _worker.js" || echo "No changes to commit"
          git push
